#!/usr/bin/env python3
"""Render per-device nginx server blocks from the canary device manifest.

The F5 Terraform provider treats `address` as a bare host and concatenates
`https://<address>:<port>/mgmt/...` with no support for a path prefix or
Host-header override (see provider.go in F5Networks/terraform-provider-bigip,
NewSession in scottdware/go-bigip). The mock multiplexes devices by
`/<hostname>/mgmt/...` path prefix, so the provider can't reach it directly.

This script reads `/manifests/canary.json` and emits one nginx server block
per device, each listening on the device's allocated port and rewriting
incoming `/mgmt/...` to the multiplexed `/<hostname>/mgmt/...` shape before
proxying to the mock-f5 container.

Trailing slashes on `proxy_pass` and `location` matter and are deliberate;
see the comment block in the rendered config.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

MANIFEST_PATH = Path(os.environ.get("MANIFEST_PATH", "/manifests/canary.json"))
OUTPUT_PATH = Path(os.environ.get("OUTPUT_PATH", "/etc/nginx/conf.d/devices.conf"))
UPSTREAM = os.environ.get("UPSTREAM", "mock-f5:8080")


def render(devices: list[dict[str, object]]) -> str:
    lines: list[str] = [
        "# Generated by render_nginx_conf.py from the device manifest.",
        f"# Source manifest: {MANIFEST_PATH}",
        f"# Upstream: {UPSTREAM}",
        "#",
        "# proxy_pass trailing-slash rule:",
        "#   location /mgmt/ {",
        "#     proxy_pass http://upstream/<hostname>/mgmt/;  # trailing / is required",
        "#   }",
        "# With the trailing slash, nginx replaces the matched /mgmt/ prefix on the",
        "# inbound URI; without it, the full inbound path is appended to the",
        "# upstream URI and the mock multiplex sees /mgmt/.../mgmt/... and 404s.",
        "",
    ]
    for entry in devices:
        hostname = entry["hostname"]
        port = entry["port"]
        lines.extend(
            [
                f"# {hostname} -> {UPSTREAM}/{hostname}/mgmt/...",
                "server {",
                # TLS on every listener; F5 provider hardcodes https://.
                f"    listen {port} ssl;",
                f"    server_name {hostname};",
                "    ssl_certificate     /etc/nginx/proxy.crt;",
                "    ssl_certificate_key /etc/nginx/proxy.key;",
                "",
                "    # Health probe used by docker compose healthcheck.",
                "    location = /health {",
                f"        proxy_pass http://{UPSTREAM}/health;",
                "    }",
                "",
                "    location /mgmt/ {",
                f"        proxy_pass http://{UPSTREAM}/{hostname}/mgmt/;",
                "        proxy_set_header Host $host;",
                "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                "        proxy_read_timeout 60s;",
                "    }",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    if not MANIFEST_PATH.exists():
        print(f"manifest not found: {MANIFEST_PATH}", file=sys.stderr)
        return 1
    data = json.loads(MANIFEST_PATH.read_text())
    devices = data.get("devices", [])
    if not devices:
        print(f"manifest {MANIFEST_PATH} lists no devices", file=sys.stderr)
        return 1
    seen_ports: set[int] = set()
    for entry in devices:
        port = int(entry["port"])
        if port in seen_ports:
            print(f"duplicate port in manifest: {port}", file=sys.stderr)
            return 1
        seen_ports.add(port)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render(devices))
    print(f"rendered {len(devices)} server blocks to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
