"""Per-extraction README generator.

Emits README.md next to as3.json + do.json + main.tf + imports.tf in
the extraction output directory. Documents what was extracted, the
adoption flow, the tenant-collision note, and the normalization
boundary that makes "byte-stable up to documented normalization" the
verifiable property ADR 007 §Scope names.

Deterministic output: NO timestamps, NO run-specific fields beyond
walker-derived counts/names which are themselves deterministic on the
same device state. The tool's pinned version is included since that's
also deterministic per release.

Lists are sorted alphabetically inside their categories so re-extraction
of identical device state produces identical README bytes. Walker output
order is preserved within the JSON declarations (which is what AS3 and
DO consume); the human-readable README applies sorting for stability.
"""

from __future__ import annotations

from brownfield.builtins import is_builtin
from brownfield.emit._shape import tf_resource_name
from brownfield.walker import WalkerOutput

# Pinned tool version. Bump when releasing a new brownfield tool version.
# Used in the emitted README so the README byte-stable check has a
# deterministic version field.
BROWNFIELD_VERSION = "0.1.0"


def emit_readme(
    walker_output: WalkerOutput,
    *,
    hostname: str,
    partition: str = "Common",
) -> str:
    """Produce README.md content for an extraction output directory."""
    resource_name = tf_resource_name(hostname, partition)
    counts = _counts(walker_output)
    return f"""# Brownfield extraction: {hostname}

Generated by `python -m brownfield extract` (brownfield {BROWNFIELD_VERSION}).
Source device: `{hostname}`.
Source partition: `{partition}`.
Tool emits against AS3 schema 3.50.0 (vendored 3.51.0 schema accepts it)
and DO schema 1.40.0 (vendored 1.47.0 schema accepts it).

## What was extracted

From F5 partition `/{partition}` on `{hostname}`:

{_summary_list(walker_output, counts)}

Filtered out as F5 built-ins per the ACC v1.24.0 list (commit `e6f9fcec`,
`src/lib/bigipDefaults.json`): {counts["filtered"]} object(s). See
`brownfield/builtins.py` for the vendored list and provenance.

## Files in this directory

- `as3.json` — AS3 declaration applying to F5 partition `/{partition}`.
  Tenant name `{partition}` (literal — see ADR 007 Addendum 2026-05-13).
- `do.json` — DO declaration matching live device system state from
  `/mgmt/shared/declarative-onboarding/inspect`.
- `imports.tf` — Terraform import block for `bigip_as3.{resource_name}`
  with partition-CSV ID `"{partition}"`.
- `main.tf` — Terraform resources for both DO + AS3 declarations.

## Adoption flow

**AS3 (`bigip_as3.{resource_name}`):** First `terraform apply` imports
`/{partition}` under Terraform management. Because the declaration was
extracted from live device state, the apply is structurally a no-op at
the F5 layer — same objects, same configuration. Terraform now tracks
`/{partition}`.

**DO (`bigip_do.{resource_name}`):** First apply uses the
**apply-no-op adoption** flow (see
[ADR 007](../../docs/decisions/007-brownfield-config-discovery.md)).
The DO declaration matches the device's current system state, so the
first POST generates a task ID without changing the device. Subsequent
applies behave normally.

**Recommended pre-apply workflow per ADR 007 §Tradeoffs:**

1. `python -m brownfield validate <this_dir>` — schema-validates
   as3.json and do.json against the vendored ADR 006 schemas.
2. `terraform plan` — review the import block; confirm no
   `create`/`update`/`delete` actions other than the import.
3. Human review of as3.json and do.json against operator intent.
4. `terraform apply`.

Never extract-and-apply in one command. The CLI's `extract` and
`validate` are separate invocations by design.

## After adoption

AS3 owns `/{partition}` on `{hostname}`. GUI/tmsh edits to objects in
this partition will surface as drift on the next `terraform plan`. The
drift gate (per ADR 002, ADR 006) catches out-of-band edits at both
schema and plan levels.

Anything in `/{partition}` outside the extraction (ASM/APM objects,
future GUI/tmsh additions, objects matching the ACC built-in filter)
is NOT covered by this declaration.

## Normalization boundary (re-extraction byte-stability)

ADR 007 §Scope of the first cut requires re-extraction byte-stability
"up to documented normalization." Documented normalizations applied
during emission:

- **Built-in filtering.** F5 built-in objects under /Common are
  excluded per the ACC v1.24.0 vendored list.
- **Partition → tenant 1:1.** AS3 tenant name = F5 partition name.
- **Hostname → TF resource name.** Hyphens normalized to underscores
  (`bigip-lab-01` → `bigip_lab_01`).
- **AS3 schema version pin.** Emitted declarations carry
  `schemaVersion: "3.50.0"` regardless of source device's installed
  AS3 version (the vendored 3.51.0 schema accepts 3.50.0).
- **DO field passthrough.** The Device declaration from `/inspect` is
  passed through with a brownfield-extraction label added; other
  fields preserve walker order.
- **README sorting.** Object lists in this README are alphabetized
  within each category for stable diffs. JSON declarations preserve
  walker output order (AS3/DO don't care about declaration order).

Re-running `brownfield extract` against unchanged device state produces
identical as3.json, do.json, main.tf, imports.tf, README.md bytes.

## Tenant-collision note

The AS3 tenant in this declaration is named `{partition}` (literal,
matches the F5 partition). If you extract `/{partition}` from multiple
devices into the same Terraform workspace, each device's extraction
produces its own resource (e.g., `bigip_as3.bigip_lab_01_Common`,
`bigip_as3.bigip_lab_02_Common`), each bound to its own provider/device.
The tenant name `{partition}` is reused inside each declaration but no
collision occurs because each resource targets a different device.
"""


def _counts(walker_output: WalkerOutput) -> dict[str, int]:
    """Count what made it through the built-in filter, what didn't.

    Members are counted across all pools (pools themselves are not
    filtered as built-ins — pool objects under /Common are operator
    content; ACC's list contains node/profile/monitor/persistence
    built-ins but not pools).
    """
    filtered = 0
    for collection in (
        walker_output.monitors_http,
        walker_output.profiles_clientssl,
        walker_output.persistence_cookie,
        walker_output.rules,
    ):
        filtered += sum(1 for item in collection if is_builtin(item))
    total_members = sum(len(p.get("_members", [])) for p in walker_output.pools)
    return {
        "virtuals": len(walker_output.virtuals),
        "pools": len(walker_output.pools),
        "members": total_members,
        "monitors": sum(1 for m in walker_output.monitors_http if not is_builtin(m)),
        "profiles": sum(1 for p in walker_output.profiles_clientssl if not is_builtin(p)),
        "persists": sum(1 for p in walker_output.persistence_cookie if not is_builtin(p)),
        "rules": sum(1 for r in walker_output.rules if not is_builtin(r)),
        "filtered": filtered,
    }


def _summary_list(walker_output: WalkerOutput, counts: dict[str, int]) -> str:
    """Render the alphabetized "what was extracted" bullet list."""
    virtuals = sorted(v["name"] for v in walker_output.virtuals)
    pools = sorted(p["name"] for p in walker_output.pools)
    monitors = sorted(m["name"] for m in walker_output.monitors_http if not is_builtin(m))
    profiles = sorted(p["name"] for p in walker_output.profiles_clientssl if not is_builtin(p))
    persists = sorted(p["name"] for p in walker_output.persistence_cookie if not is_builtin(p))
    rules = sorted(r["name"] for r in walker_output.rules if not is_builtin(r))
    lines = [
        f"- {counts['virtuals']} virtual server(s): {', '.join(virtuals) or '(none)'}",
        f"- {counts['pools']} pool(s): {', '.join(pools) or '(none)'} "
        f"({counts['members']} total members)",
        f"- {counts['monitors']} HTTP monitor(s): {', '.join(monitors) or '(none)'}",
        f"- {counts['profiles']} ClientSSL profile(s): {', '.join(profiles) or '(none)'}",
        f"- {counts['persists']} cookie persistence profile(s): {', '.join(persists) or '(none)'}",
        f"- {counts['rules']} iRule(s): {', '.join(rules) or '(none)'}",
        "- System DO declaration: hostname, DNS, NTP, syslog, provisioning, VLANs, "
        "self-IPs (extracted via /mgmt/shared/declarative-onboarding/inspect)",
    ]
    return "\n".join(lines)
