"""Terraform file emission: main.tf + imports.tf.

Per ADR 007 §Decision #3 and Addendum 2026-05-13:

- bigip_as3 gets an `import` block with partition-CSV ID (just the
  partition name for our single-tenant first cut).
- bigip_do follows apply-no-op adoption: a `resource` block with the
  extracted do.json as do_json, NO import block. First apply is a
  structural no-op at the F5 layer and brings the resource under
  Terraform management with a real task UUID.

Output is deterministic: same hostname + partition → same HCL bytes.
Comments cite the ADRs so readers can find the why.
"""

from __future__ import annotations

from brownfield.emit._shape import tf_resource_name


def emit_terraform(*, hostname: str, partition: str = "Common") -> dict[str, str]:
    """Return {'main.tf': ..., 'imports.tf': ...}.

    Both files are HCL strings ready to write to the extraction output
    directory. The provider block is in main.tf; imports.tf is
    independently runnable (`terraform import` operations have moved
    to import blocks in recent Terraform, which run during apply).
    """
    resource_name = tf_resource_name(hostname, partition)
    return {
        "main.tf": _main_tf(hostname=hostname, partition=partition, resource_name=resource_name),
        "imports.tf": _imports_tf(partition=partition, resource_name=resource_name),
    }


def _main_tf(*, hostname: str, partition: str, resource_name: str) -> str:
    return f"""# Generated by brownfield extractor (tools/brownfield) per ADR 007.
# DO NOT hand-edit — re-run `python -m brownfield extract` to refresh.
#
# Resource naming: <hostname>_<partition> with hyphens normalized to
# underscores per ADR 007 Addendum 2026-05-13. AS3 tenant inside as3.json
# is the literal partition name `{partition}`; multi-device
# disambiguation lives at the Terraform resource name layer.

terraform {{
  required_providers {{
    bigip = {{
      source  = "F5Networks/bigip"
      version = "~> 1.26"
    }}
  }}
}}

# Adopt /{partition} on {hostname} into declarative source of truth.
# First `terraform apply` after `terraform import` (see imports.tf) is
# a structural no-op at the F5 layer because the declaration was
# extracted from live device state.
resource "bigip_as3" "{resource_name}" {{
  as3_json = file("${{path.module}}/as3.json")
}}

# DO adoption uses the apply-no-op flow (ADR 007 § bigip_do import).
# The bigip_do provider requires a task UUID for import, which doesn't
# exist on a brownfield device — the first apply POSTs the extracted
# declaration (structural no-op at F5; DO sees no diff) and captures
# the resulting task UUID in state. NO import block for bigip_do.
resource "bigip_do" "{resource_name}" {{
  do_json = file("${{path.module}}/do.json")
}}
"""


def _imports_tf(*, partition: str, resource_name: str) -> str:
    return f"""# Generated by brownfield extractor per ADR 007 §Decision #3.
#
# AS3 import: ID is the partition-name CSV. For our single-tenant first
# cut that's just the partition `{partition}`. Source for import shape:
# https://github.com/F5Networks/terraform-provider-bigip/blob/master/docs/resources/bigip_as3.md
#
# No import block for bigip_do — see main.tf for the apply-no-op flow.

import {{
  to = bigip_as3.{resource_name}
  id = "{partition}"
}}
"""
